<a href="https://colab.research.google.com/github/farhanasajeer/Machine-learning/blob/main/saved_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv('/content/drive/MyDrive/homeprices.csv')
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [3]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([118.29495955])

In [5]:
model.intercept_

257056.627255756

In [6]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([848531.42501556])

In [7]:
# save model to a file using python pickle
import pickle

In [8]:
with open('model_pickle','wb') as file:
  pickle.dump(model,file)

In [9]:
# load saved model
with open('model_pickle','rb') as file:
  mp=pickle.load(file)

In [10]:
mp.coef_

array([118.29495955])

In [11]:
mp.intercept_

257056.627255756

In [12]:
mp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([848531.42501556])

In [13]:
# sved trained model using joblib
import joblib
joblib.dump(model,'model_joblib')

['model_joblib']

In [14]:
# load saved model
mj=joblib.load('model_joblib')

In [15]:
mj.coef_

array([118.29495955])

In [16]:
mj.intercept_

257056.627255756

In [17]:
mj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([848531.42501556])